### ISSUE TITLE
making the visual highlight more obvious

### ISSUE THREAD

**Issue by bryant-the-coder** [tiagovla/tokyodark.nvim#11]
please make the visual highlighting more obvious. kinda hard to see where i m highlighting

**Comment by tiagovla** [comment]
A higher contrast between these?
![image](https://user-images.githubusercontent.com/30515389/149052127-d0289536-7ac7-42e9-b703-51eedc35252b.png)

**Comment by bryant-the-coder** [comment]
u press V can u see where the selection is? for me no lol... so i was just asking if it is possible

**Comment by bryant-the-coder** [comment]
thanks
