### ISSUE TITLE
support for iterm2

### ISSUE THREAD

**Issue by LuisxSullivaN** [tiagovla/tokyodark.nvim#12]
i'm loving this theme, do you think we can have this colorscheme for iterm2?

**Comment by tiagovla** [comment]
Is there a config file for it? I have only used alacritty/kitty.

**Comment by LuisxSullivaN** [comment]
hey - sure! there is [this one](https://github.com/catppuccin/iterm/blob/main/catppuccin.itermcolors) which you can take a look
