### ISSUE TITLE
conflicts in '/.../packer/start/tokyodark.nvim/lua/tokyodark/highlights.lua'

### ISSUE THREAD

**Issue by n-kev1n** [tiagovla/tokyodark.nvim#14]
### The errors showed up after updating 
![tokyodark-issue](https://user-images.githubusercontent.com/94931973/154799555-17c970f8-0ae1-4a9b-8352-7c03c0140d6f.png)

**Comment by tiagovla** [comment]
@n-kev1n I looked into it and I think this is a neovim bug. I opened an issue there.
The latest neovim commit that is still working is `b94b11623622abc607ed86a2ad148d6134f80d15`.

**Comment by tiagovla** [comment]
@n-kev1n good news! They merged https://github.com/neovim/neovim/commit/1e7cb2dcd975aadeb91b913f117b21c7775c3374.
