### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by cunderw** [tiagovla/tokyodark.nvim#18]
Latest update throws errors when launching nvim.

![image](https://user-images.githubusercontent.com/29203283/197069668-83f8524f-6c8b-422e-9fd9-3b6f969ecb63.png)

**Comment by tiagovla** [comment]
What's your neovim version?

**Comment by tiagovla** [comment]
This only happens in older versions of neovim. I patched it for now, but please consider updating your neovim version. Today, 0.8 is stable and 0.9 is nightly.

**Comment by cunderw** [comment]
I was running an older 0.8 dev release, can confirm it works now with pre .08, and 0.8+.
