### ISSUE TITLE
flash.nvim highlights are of same colors

### ISSUE THREAD

**Issue by niksingh710** [tiagovla/tokyodark.nvim#21]
if using flash.nvim plugin and using `f` key to highlight the occurence of a character the current position of cursor color is same while jumping on the next occurence.

**Comment by tiagovla** [comment]
@niksingh710 Could you test the changes?

**Comment by niksingh710** [comment]
> @niksingh710 Could you test the changes?

The color have changed, but yet the problem remains.

Every highlight matching the character is of the same color including the cursor, so moving the cursor to the next occurrence make it impossible to know the location of the cursor

**Comment by tiagovla** [comment]
> > @niksingh710 Could you test the changes?
> 
> Every highlight matching the character is of the same color including the cursor, so moving the cursor to the next occurrence make it impossible to know the location of the cursor

This is how it looks for me:
![image](https://github.com/tiagovla/tokyodark.nvim/assets/30515389/b3989b58-1216-4dc5-82a1-86960639b6a5)

**Comment by niksingh710** [comment]
![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/81ef470f-b8b1-4aa9-8087-045bb09a2bb8)
This is how it looks to me.

i opened my config then pressed `f` and `r` now if i keep pressing f to go to next occurrence of `r` character it's impossible to find where the cursor is.

Here the same in tokyonight
![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/8df83565-c83d-4353-b363-d371ebe916ac)
![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/57019e98-795a-4a23-b4db-fa749fbcae7d)
in both e.g of tokyonight the current position of cursor is highlighted by different colour.

**Comment by niksingh710** [comment]
> Could you try it on another terminal? The cursor should be inverted.

Just tried with alacritty working fine but not on foot terminal have to figure out why it is happening.

**Comment by niksingh710** [comment]
Fixed it.

If someone else stumbles over this using foot. make sure you have manually setted cursor color in foot.ini
e.g
```
[cursor]
style=beam
color=421a38 000000  # foreground background
blink=yes
```
