### ISSUE TITLE
highlights for dap?

### ISSUE THREAD

**Issue by niksingh710** [tiagovla/tokyodark.nvim#23]
DapLogPoint
DapBreakpoint
DapStopped

will it be possible to have highlights for dap in the theme?

**Comment by tiagovla** [comment]
Yep, gonna check it when I get some free time.

**Comment by tiagovla** [comment]
Could you share a screenshot showing where those highlights are placed using DAP?

**Comment by niksingh710** [comment]
> Could you share a screenshot showing where those highlights are placed using DAP?

![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/c13cd776-072e-4eab-bed8-46c0660d5794)

here the bug icons is what that need to be colored.

```lua
vim.fn.sign_define(
	"DapBreakpoint",
	{ text = icons.ui.Bug, texthl = "DapBreakpoint", linehl = "DapBreakpoint", numhl = "DapBreakpoint" }
)
vim.fn.sign_define(
	"DapBreakpointCondition",
	{ text = "ﳁ", texthl = "DapBreakpoint", linehl = "DapBreakpoint", numhl = "DapBreakpoint" }
)
vim.fn.sign_define(
	"DapBreakpointRejected",
	{ text = icons.ui.Bug, texthl = "DapBreakpoint", linehl = "DapBreakpoint", numhl = "DapBreakpoint" }
)
vim.fn.sign_define(
	"DapLogPoint",
	{ text = icons.diagnostics.BoldInformation, texthl = "DapLogPoint", linehl = "DapLogPoint", numhl = "DapLogPoint" }
)
vim.fn.sign_define(
	"DapStopped",
	{ text = icons.ui.BoldArrowRight, texthl = "DapStopped", linehl = "DapStopped", numhl = "DapStopped" }
)

vim.api.nvim_set_hl(0, "DapBreakpoint", { fg = "#993939", bg = nil })
vim.api.nvim_set_hl(0, "DapLogPoint", { fg = "#61afef", bg = nil })
vim.api.nvim_set_hl(0, "DapStopped", { fg = "#98c379", bg = nil })

```
This is what i got from their github but it only works if i source it manually

sorry for the late response was busy.

**Comment by tiagovla** [comment]
Thanks! I will look into it. If you want to use custom highlights, you could try those like this:
```lua
require("tokyodark").setup {
    custom_highlights = {
        DapBreakpoint = { fg = "#993939" },
        DapLogPoint = { fg = "#61afef" },
        DapStopped = { fg = "#98c379" },
    },
}
-- before calling the colorscheme
```

**Comment by niksingh710** [comment]
> 

This throws an error failed to call setup on a nil value
h
```lua
{
		"tiagovla/tokyodark.nvim",
		config = function()
			require("tokyodark").setup({
				custom_highlights = {
					DapBreakpoint = { fg = "#993939" },
					DapLogPoint = { fg = "#61afef" },
					DapStopped = { fg = "#98c379" },
				},
			})
		end,
	},
```
lazy config

**Comment by niksingh710** [comment]
> > 
> 
> This throws an error failed to call setup on a nil value h
> 
> ```lua
> {
> 		"tiagovla/tokyodark.nvim",
> 		config = function()
> 			require("tokyodark").setup({
> 				custom_highlights = {
> 					DapBreakpoint = { fg = "#993939" },
> 					DapLogPoint = { fg = "#61afef" },
> 					DapStopped = { fg = "#98c379" },
> 				},
> 			})
> 		end,
> 	},
> ```
> 
> lazy config

seems like this was cause i was not on latest commit. now working as expected after updating
