### ISSUE TITLE
Absence of specific color for Lualine when in 'command' mode

### ISSUE THREAD

**Issue by shreyas-a-s** [tiagovla/tokyodark.nvim#33]
As you can see in the video, all modes have their own Lualine colors but no specific color for command mode:

[Screencast from 2024-03-09 01-26-03.webm](https://github.com/tiagovla/tokyodark.nvim/assets/137637016/31fc129e-d01f-4f35-be53-b5b050e7c06a)

It would be nice to set a nice and separate color (eg: yellow) for the command mode.

It's a simple addition and I can do a pull request if you could say which color you would prefer for it.

**Comment by shreyas-a-s** [comment]
Same case with me. I also only noticed when I started using noice.nvim for cmdline.

Certainly. It's a simple code addition. I can do a pull request.

Which color would you prefer for the command mode? Is yellow ok? Like in this gif:

![noice](https://github.com/shreyas-a-s/dotfiles/assets/137637016/46f6569e-5e10-4117-848c-2ef3b31dd54e)

**Comment by tiagovla** [comment]
Yeah.

**Comment by shreyas-a-s** [comment]
PR submitted.
