### ISSUE TITLE
Transparency for latex concealed items.

### ISSUE THREAD

**Issue by niksingh710** [tiagovla/tokyodark.nvim#40]
### Neovim version

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Description

![image](https://github.com/tiagovla/tokyodark.nvim/assets/60490474/2b6d9367-c101-4a1f-96cb-0463a5dbb7e9)

Here x^2 is concealed by latex ig. but it does not have a transparent bg How can i fix that?

**Comment by tiagovla** [comment]
Sorry for the late reply. I was traveling. This patch should fix it. You can customize the `Conceal` highlight group if needed.

**Comment by niksingh710** [comment]
Ty, It is fixed in the latest commit.
