### ISSUE TITLE
Errors Are The Color Pink

### ISSUE THREAD

**Issue by NightRaven055** [tiagovla/tokyodark.nvim#9]
Is there anyway you can change the color to like light dark. For other themes it's not pink any idea ?

<img width="967" alt="Screenshot 2021-12-05 at 16 48 58" src="https://user-images.githubusercontent.com/92249741/144755542-ff0ffd38-b839-40a0-b27e-2f5f723e94fc.png">

**Comment by tiagovla** [comment]
That should not be like that. Does it also happen with other languages? Could you test it with python? It's only happening with coc virtual text? I will try to reproduce it.

**Comment by NightRaven055** [comment]
Hi sorry for the late response but it is with python too.
<img width="1440" alt="Screenshot 2021-12-07 at 16 41 02" src="https://user-images.githubusercontent.com/92249741/145070032-793b08d7-565f-45c4-94f5-de6b4de308f8.png">

**Comment by tiagovla** [comment]
@NightRaven055 Could you check if it's working?

**Comment by NightRaven055** [comment]
Yep it is fixed now thanks so much.
<img width="1440" alt="Screenshot 2021-12-10 at 07 26 09" src="https://user-images.githubusercontent.com/92249741/145534292-ca4ea184-6f19-4c45-a553-5d03e0381db5.png">
